[workspace]
members = [
    "crates/axor",
    "crates/axor-macros",
    "crates/axor-web",
    #"crates/axor-web",
    # "crates/axor-tauri",
    # "crates/axor-cli",
    # "crates/axor-doc",
]

resolver = "2"
